#!/usr/bin/env bash
# Install certbot and dependencies

apt-get update
apt-get install -y certbot openssl

# Generate SSL certificate with certbot
certbot certonly --standalone --agree-tos --non-interactive --email avit.mugisha@gmail.com -d www.thesesame.tech

# Configure HAproxy for SSL termination
echo "frontend https
  bind *:443 ssl crt /etc/letsencrypt/live/www.thesesame.tech/fullchain.pem
  http-request redirect scheme https unless { ssl_fc }
  default_backend www-backend

backend www-backend
  balance roundrobin
  server web1 10.0.0.2:80 check
  server web2 10.0.0.3:80 check" > /etc/haproxy/haproxy.cfg

# Restart HAproxy
systemctl restart haproxy.service
